import Foundation
import FoundationModels
import GameplayKit

/// A word-clue pair generated by Apple Intelligence.
@Generable
struct GeneratedWordClue: Equatable {
  @Guide(
    description:
      "A single everyday English word, 3 to 6 letters, uppercase, letters only, no proper nouns, abbreviations, or obscure crosswordese (overly specialized crossword vocabulary)"
  )
  var word: String

  @Guide(
    description:
      "A complete, concise crossword-style clue for the word, 2 to 8 words long, must not contain the answer word. Must be a grammatically complete phrase or definition — never end with a preposition (of, for, with, in, at, by, from, to), article (a, an, the), conjunction (and, or, but), or an incomplete modifier"
  )
  var clue: String
}

/// A batch of word-clue pairs for puzzle generation.
@Generable
struct WordClueBatch: Equatable {
  @Guide(description: "A list of unique word-clue pairs for a crossword puzzle", .count(15))
  var entries: [GeneratedWordClue]
}

/// Generates word-clue pairs using Apple Intelligence on-device language model.
/// Falls back to the bundled wordlist when Apple Intelligence is unavailable.
final class AIWordService: Sendable {
  static let shared = AIWordService()

  struct GenerationResult: Sendable {
    let words: [WordClue]
    let status: AIGenerationStatus
    let detail: String?
  }

  /// Words that, when appearing last in a clue, indicate an incomplete sentence.
  private static let incompleteClueEnders: Set<String> = [
    "a", "an", "the",
    "of", "for", "with", "in", "at", "by", "from", "to", "into", "onto", "upon",
    "and", "or", "but", "nor", "yet",
    "is", "are", "was", "were",
    "consisting", "having", "using", "including", "containing", "made", "composed",
  ]

  private let fallbackService = WordListService.shared

  /// Whether Apple Intelligence is available on this device.
  var isAvailable: Bool {
    SystemLanguageModel.default.availability == .available
  }

  /// Number of batch requests to make to accumulate enough AI-generated entries.
  private static let batchRounds = 3
  /// Minimum fraction of requested count that must pass validation to use AI output.
  private static let minimumValidFraction = 0.3

  /// Maximum time in seconds to wait for all AI batch rounds before falling back.
  static let aiTimeoutSeconds: TimeInterval = 18

  /// Generate a batch of word-clue pairs for a puzzle.
  /// Uses Apple Intelligence if available, otherwise falls back to bundled list.
  /// Makes multiple batch requests to accumulate enough entries (each batch returns up to 15).
  /// Falls back to bundled list if AI doesn't finish within the timeout.
  /// Returns the words along with generation diagnostics for developer mode.
  func generateWordClues(count: Int, maxLength: Int, seed: UInt64) async -> GenerationResult {
    guard isAvailable else {
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        status: .appleIntelligenceUnavailable,
        detail: nil
      )
    }

    do {
      return try await withThrowingTaskGroup(of: GenerationResult.self) { group in
        group.addTask {
          try await self.generateWithAI(count: count, maxLength: maxLength, seed: seed)
        }
        group.addTask {
          try await Task.sleep(for: .seconds(Self.aiTimeoutSeconds))
          throw AITimeoutError()
        }

        // Return whichever finishes first; if AI wins we get its result,
        // if the timeout wins the AI task is cancelled and we fall back.
        if let result = try await group.next() {
          group.cancelAll()
          return result
        }

        // Should not reach here, but fall back just in case.
        return GenerationResult(
          words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
          status: .generationRequestFailed,
          detail: "Unexpected timeout state."
        )
      }
    } catch is AITimeoutError {
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        status: .generationRequestFailed,
        detail: "AI generation timed out after \(Int(Self.aiTimeoutSeconds))s."
      )
    } catch {
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        status: .generationRequestFailed,
        detail: error.localizedDescription
      )
    }
  }

  private struct AITimeoutError: Error {}

  /// The actual AI generation logic, extracted so it can be raced against a timeout.
  private func generateWithAI(count: Int, maxLength: Int, seed: UInt64) async throws
    -> GenerationResult
  {
    let instructions = """
      You are a crossword puzzle creator. Generate unique, common English words \
      with concise crossword-style clues. Rules:
      - Words must be \(3) to \(maxLength) letters long
      - Words must be UPPERCASE, letters only (A-Z)
      - No proper nouns, no offensive words
      - Prefer everyday vocabulary that most adults and older children would know
      - Avoid obscure crosswordese, abbreviations, jargon, archaic terms, and very rare words
      - Clues must be 2-8 words, must NOT contain the answer word
      - Clues must be COMPLETE phrases or definitions — never truncated or cut off mid-sentence
      - Clues must never end with a preposition (of, for, with, in, at, by, from, to),
      article (a, an, the), conjunction (and, or, but), or a dangling modifier
      - Clues should be clever and concise, like newspaper crossword clues
      - All words must be different from each other
      - Mix word lengths: include some 3-letter, some 4-letter, some 5-letter words
      """
    let session = LanguageModelSession(instructions: instructions)

    var allGenerated: [WordClue] = []
    var seenWords: Set<String> = []

    for round in 0..<Self.batchRounds {
      try Task.checkCancellation()

      let roundPrompt: String
      if round == 0 {
        roundPrompt =
          "Generate unique crossword word-clue pairs with words of \(3)-\(maxLength) letters using broadly familiar, everyday vocabulary."
      } else {
        let avoid = seenWords.sorted().joined(separator: ", ")
        roundPrompt =
          "Generate more unique crossword word-clue pairs with words of \(3)-\(maxLength) letters. Do NOT reuse these words: \(avoid)."
      }

      let response = try await session.respond(
        to: roundPrompt,
        generating: WordClueBatch.self
      )

      let validated = response.content.entries.compactMap { entry -> WordClue? in
        let word = entry.word.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
        let clue = entry.clue.trimmingCharacters(in: .whitespacesAndNewlines)

        guard word.count >= 3, word.count <= maxLength,
          word.allSatisfy({ $0.isLetter && $0.isASCII }),
          !clue.isEmpty,
          !seenWords.contains(word)
        else {
          return nil
        }

        let lastWord =
          clue
          .components(separatedBy: .whitespaces)
          .last?
          .lowercased()
          .trimmingCharacters(in: .punctuationCharacters) ?? ""
        guard !AIWordService.incompleteClueEnders.contains(lastWord) else {
          return nil
        }

        return WordClue(word: word, clue: clue)
      }

      for entry in validated {
        seenWords.insert(entry.word)
        allGenerated.append(entry)
      }

      if allGenerated.count >= count { break }
    }

    let minimumRequired = max(Int(Double(count) * Self.minimumValidFraction), 1)

    if allGenerated.count >= minimumRequired {
      var results = allGenerated
      let supplemented = results.count < count
      if supplemented {
        let extra = fallbackWords(count: count - results.count, maxLength: maxLength, seed: seed)
          .filter { !seenWords.contains($0.word) }
        results.append(contentsOf: extra)
      }
      return GenerationResult(
        words: Array(results.prefix(count)),
        status: supplemented ? .generatedWithAISupplement : .generatedWithAI,
        detail: supplemented
          ? "Accepted \(allGenerated.count) validated AI entries and supplemented with bundled words."
          : "Accepted \(allGenerated.count) validated AI entries."
      )
    }

    return GenerationResult(
      words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
      status: .validationFailed,
      detail:
        "Accepted \(allGenerated.count) validated AI entries; required at least \(minimumRequired) to use AI output."
    )
  }

  /// Fallback: return words from the bundled wordlist.
  private func fallbackWords(count: Int, maxLength: Int, seed: UInt64) -> [WordClue] {
    let all = fallbackService.entries.filter {
      $0.word.count >= 3 && $0.word.count <= maxLength
    }
    var rng = GKMersenneTwisterRandomSource(seed: seed)
    var shuffled = all
    shuffled.shuffle(using: &rng)
    return Array(shuffled.prefix(count))
  }
}
