import Foundation
import FoundationModels
import GameplayKit
import os

private let logger = Logger(subsystem: "com.timheuer.gridlet", category: "AIWordService")

/// A word-clue pair generated by Apple Intelligence.
@Generable
struct GeneratedWordClue: Equatable {
  @Guide(
    description:
      "An English word, uppercase, letters only. No proper nouns, abbreviations, or obscure jargon"
  )
  var word: String

  @Guide(
    description:
      "A clever, concise crossword-style clue for the word, 2 to 8 words long. Must not contain the answer word or any form of it. Must be a complete phrase — never end mid-thought"
  )
  var clue: String
}

/// A batch of word-clue pairs for puzzle generation.
@Generable
struct WordClueBatch: Equatable {
  @Guide(description: "A list of unique word-clue pairs for a crossword puzzle", .count(10))
  var entries: [GeneratedWordClue]
}

/// Generates word-clue pairs using Apple Intelligence on-device language model.
/// Falls back to the bundled wordlist when Apple Intelligence is unavailable.
final class AIWordService: Sendable {
  static let shared = AIWordService()

  struct GenerationResult: Sendable {
    let words: [WordClue]
    /// The set of words (uppercased) that were genuinely AI-generated (not fallback supplement).
    let aiGeneratedWords: Set<String>
    let status: AIGenerationStatus
    let detail: String?
  }

  /// Words that, when appearing last in a clue, indicate an incomplete sentence.
  /// Only includes words that are almost never valid as final words in a clue.
  private static let incompleteClueEnders: Set<String> = [
    "a", "an", "the",
    "of", "with", "into", "onto", "upon",
    "and", "or", "but", "nor",
    "is", "are", "was", "were",
    "consisting", "having", "using", "including", "containing", "composed",
  ]

  private let fallbackService = WordListService.shared

  /// Whether Apple Intelligence is available on this device.
  var isAvailable: Bool {
    SystemLanguageModel.default.availability == .available
  }

  /// Number of batch requests to make to accumulate enough AI-generated entries.
  private static let batchRounds = 3
  /// Minimum fraction of requested count that must pass validation to use AI output.
  private static let minimumValidFraction = 0.3

  /// Maximum time in seconds to wait for all AI batch rounds before falling back.
  static let aiTimeoutSeconds: TimeInterval = 18

  /// Generate a batch of word-clue pairs for a puzzle.
  /// Uses Apple Intelligence if available, otherwise falls back to bundled list.
  /// Makes multiple batch requests to accumulate enough entries (each batch returns up to 15).
  /// Falls back to bundled list if AI doesn't finish within the timeout.
  /// Returns the words along with generation diagnostics for developer mode.
  func generateWordClues(count: Int, maxLength: Int, seed: UInt64) async -> GenerationResult {
    guard isAvailable else {
      logger.info("Apple Intelligence unavailable — using bundled fallback words")
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        aiGeneratedWords: [],
        status: .appleIntelligenceUnavailable,
        detail: nil
      )
    }

    do {
      return try await withThrowingTaskGroup(of: GenerationResult.self) { group in
        group.addTask {
          try await self.generateWithAI(count: count, maxLength: maxLength, seed: seed)
        }
        group.addTask {
          try await Task.sleep(for: .seconds(Self.aiTimeoutSeconds))
          throw AITimeoutError()
        }

        // Return whichever finishes first; if AI wins we get its result,
        // if the timeout wins the AI task is cancelled and we fall back.
        if let result = try await group.next() {
          group.cancelAll()
          return result
        }

        // Should not reach here, but fall back just in case.
        return GenerationResult(
          words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
          aiGeneratedWords: [],
          status: .generationRequestFailed,
          detail: "Unexpected timeout state."
        )
      }
    } catch is AITimeoutError {
      logger.warning("AI generation timed out after \(Int(Self.aiTimeoutSeconds))s — falling back to bundled list")
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        aiGeneratedWords: [],
        status: .generationRequestFailed,
        detail: "AI generation timed out after \(Int(Self.aiTimeoutSeconds))s."
      )
    } catch {
      logger.error("AI generation failed: \(error.localizedDescription) — falling back to bundled list")
      return GenerationResult(
        words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
        aiGeneratedWords: [],
        status: .generationRequestFailed,
        detail: error.localizedDescription
      )
    }
  }

  private struct AITimeoutError: Error {}

  /// The actual AI generation logic, extracted so it can be raced against a timeout.
  private func generateWithAI(count: Int, maxLength: Int, seed: UInt64) async throws
    -> GenerationResult
  {
    let instructions = """
      You are an expert newspaper crossword constructor generating entries for a small crossword puzzle (5x5, 6x6, or 7x7 grid).

      Generate engaging English crossword entries with clever crossword-style clues.

      ANCHOR ENTRIES
      First generate exactly 3 anchor words that are 6-\(maxLength) letters long.
      Anchor words should be vivid, familiar, image-evoking, and fun for a crossword.
      Prefer strong, concrete words like things, places, actions, or natural imagery.
      Do not make all anchor words share the same letter pattern.

      SUPPORTING ENTRIES
      Then generate exactly 25 additional entries.

      WORD RULES
      - Words must be 3 to \(maxLength) letters long
      - Never exceed \(maxLength) letters
      - Include at least 4 three-letter words
      - Include a good mix of 4-, 5-, 6-, and \(maxLength)-letter words when possible
      - Words must be UPPERCASE letters only (A-Z)
      - No proper nouns
      - No offensive words
      - No slang-heavy or overly obscure terms
      - All words must be unique within the batch

      CROSSWORD-FRIENDLY LETTER RULES
      - Prefer words with a healthy mix of vowels and consonants
      - Prefer common crossword-friendly letters like A, E, R, S, T, L, N
      - Prefer vivid, common, or interesting vocabulary
      - Avoid excessive repeated letters
      - Avoid words with awkward letter patterns or rare endings unless the word is very common
      - Avoid obscure crossword filler such as ETA, ERE, ORE, OLE, ALA
      - Avoid repeating the same starting letter more than twice

      VOCABULARY STYLE
      Prefer words from everyday language, nature, weather, food, animals, objects, actions, places, or emotions.
      Favor words that create a strong mental image.

      CLUE RULES
      - Every word must include a crossword-style clue
      - Clues must be 2-8 words
      - Clues must not contain the answer word or any form of it
      - Clues should be witty, indirect, playful, metaphorical, or lightly clever when possible
      - Avoid plain dictionary definitions when possible
      - Clues must read like complete natural phrases, never sentence fragments cut off mid-thought

      GOOD EXAMPLES
      OAK — Forest giant with acorns
      OWL — Silent hunter of the night
      INK — Writer's bottled thoughts
      ICE — Skater's frozen stage
      JAM — Toast's sticky partner
      BLOOM — Garden's grand opening
      QUEST — Knight's wandering mission
      SPARK — Tiny idea igniter
      CRISP — Apple texture at harvest

      OUTPUT FORMAT
      Return exactly 28 entries total.
      Return only entries in this exact format:
      WORD — clue

      Do not number the entries.
      Do not add categories, explanations, headings, or extra text.
      """
    let session = LanguageModelSession(instructions: instructions)

    var allGenerated: [WordClue] = []
    var seenWords: Set<String> = []

    for round in 0..<Self.batchRounds {
      try Task.checkCancellation()

      let roundPrompt: String
      if round == 0 {
        roundPrompt =
          "Generate crossword word-clue pairs. All words must be 3 to \(maxLength) letters. Include some 3-letter words. Use clever, indirect clues."
      } else {
        let avoid = seenWords.sorted().joined(separator: ", ")
        roundPrompt =
          "Generate more crossword word-clue pairs, all 3 to \(maxLength) letters. Include some 3-letter words. Use clever clues. Do NOT reuse: \(avoid)."
      }

      let response = try await session.respond(
        to: roundPrompt,
        generating: WordClueBatch.self
      )

      let validated = response.content.entries.compactMap { entry -> WordClue? in
        let word = entry.word.uppercased().trimmingCharacters(in: .whitespacesAndNewlines)
        let clue = entry.clue.trimmingCharacters(in: .whitespacesAndNewlines)

        // Reject clues that contain the answer word (case-insensitive)
        let clueWords = Set(
          clue.uppercased()
            .components(separatedBy: .whitespaces)
            .map { $0.trimmingCharacters(in: .punctuationCharacters) }
        )

        if word.count < 3 || word.count > maxLength {
          logger.debug("Rejected '\(word)': length \(word.count) out of range 3-\(maxLength)")
          return nil
        }
        if !word.allSatisfy({ $0.isLetter && $0.isASCII }) {
          logger.debug("Rejected '\(word)': contains non-ASCII or non-letter characters")
          return nil
        }
        if clue.isEmpty {
          logger.debug("Rejected '\(word)': empty clue")
          return nil
        }
        if seenWords.contains(word) {
          logger.debug("Rejected '\(word)': duplicate word")
          return nil
        }
        if clueWords.contains(word) {
          logger.debug("Rejected '\(word)': clue '\(clue)' contains the answer word")
          return nil
        }

        let lastWord =
          clue
          .components(separatedBy: .whitespaces)
          .last?
          .lowercased()
          .trimmingCharacters(in: .punctuationCharacters) ?? ""
        if AIWordService.incompleteClueEnders.contains(lastWord) {
          logger.debug("Rejected '\(word)': clue '\(clue)' ends with incomplete word '\(lastWord)'")
          return nil
        }

        logger.debug("Accepted '\(word)' → '\(clue)'")
        return WordClue(word: word, clue: clue)
      }

      logger.info("Round \(round + 1)/\(Self.batchRounds): AI returned \(response.content.entries.count) entries, \(validated.count) passed validation")

      for entry in validated {
        seenWords.insert(entry.word)
        allGenerated.append(entry)
      }

      if allGenerated.count >= count { break }
    }

    let minimumRequired = max(Int(Double(count) * Self.minimumValidFraction), 1)
    let aiWordSet = Set(allGenerated.map { $0.word })
    logger.info("AI generation complete: \(allGenerated.count) validated words (minimum required: \(minimumRequired))")

    if allGenerated.count >= minimumRequired {
      var results = allGenerated
      let supplemented = results.count < count
      if supplemented {
        let needed = count - results.count
        let extra = fallbackWords(count: needed, maxLength: maxLength, seed: seed)
          .filter { !seenWords.contains($0.word) }
        logger.info("Supplementing with \(extra.count) bundled words (had \(results.count)/\(count) from AI)")
        results.append(contentsOf: extra)
      }
      return GenerationResult(
        words: Array(results.prefix(count)),
        aiGeneratedWords: aiWordSet,
        status: supplemented ? .generatedWithAISupplement : .generatedWithAI,
        detail: supplemented
          ? "Accepted \(allGenerated.count) validated AI entries and supplemented with bundled words."
          : "Accepted \(allGenerated.count) validated AI entries."
      )
    }

    logger.warning("AI validation failed: only \(allGenerated.count) words passed (needed \(minimumRequired)) — falling back to bundled list")
    return GenerationResult(
      words: fallbackWords(count: count, maxLength: maxLength, seed: seed),
      aiGeneratedWords: [],
      status: .validationFailed,
      detail:
        "Accepted \(allGenerated.count) validated AI entries; required at least \(minimumRequired) to use AI output."
    )
  }

  /// Fallback: return words from the bundled wordlist.
  private func fallbackWords(count: Int, maxLength: Int, seed: UInt64) -> [WordClue] {
    let all = fallbackService.entries.filter {
      $0.word.count >= 3 && $0.word.count <= maxLength
    }
    var rng = GKMersenneTwisterRandomSource(seed: seed)
    var shuffled = all
    shuffled.shuffle(using: &rng)
    return Array(shuffled.prefix(count))
  }
}
